name: Deploy Next.js app to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # If you like the "detect package manager" logic, you can keep it.
      # For simplicity, we'll assume you're using npm in codelka.
      - name: Install dependencies
        run: |
          cd codelka
          npm ci

      - name: Build Next.js
        run: |
          cd codelka
          npm run build

      - name: Export Next.js (static files to `out/`)
        run: |
          cd codelka
          npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the `out/` folder located inside codelka
          path: codelka/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
